AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auto.am scrapper

  The project is aimed to scrape car data from https://auto.am/.

Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  OrchestratorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/state-machine/orchestrator.yaml
      DefinitionSubstitutions:
        GetPageCountArn: !GetAtt GetPageCount.Arn
        PageScrapperFunctionArn: !GetAtt PageScrapperFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref GetPageCount
        - LambdaInvokePolicy:
            FunctionName: !Ref PageScrapperFunction
      
  ScrapperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile

  GetPageCount:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-page-count/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
      - !Ref ScrapperLayer

  PageScrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/page-scrapper/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ScrappedURLQueue
      Layers:
      - !Ref ScrapperLayer

  ScrappedURLsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ScrappedUrls
