on:
  push:
    branches: [ main ]

name: deploy to aws

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build lambdas
        run: sam build

      - name: Deploy lambdas
        run: sam deploy --role-arn $CF_ROLE_ARN --no-confirm-changeset --parameter-overrides AutoAMAddress=$AUTOAM_IP_ADDRESS VpcId=$AWS_VPC_ID SubnetIds=$AWS_SUBNET_IDS
        env:
          AUTOAM_IP_ADDRESS: ${{ secrets.AUTOAM_IP_ADDRESS }}
          AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
          AWS_SUBNET_IDS: ${{ secrets.AWS_SUBNET_IDS }}
          CF_ROLE_ARN: ${{ secrets.CF_ROLE_ARN }}
